// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB5mCB_BhXnw1nakUa9sf2xbh5dkVvnjs',
    appId: '1:412250890587:web:84eaab12fa0fba24aefa7e',
    messagingSenderId: '412250890587',
    projectId: 'delivery-app-f28d7',
    authDomain: 'delivery-app-f28d7.firebaseapp.com',
    storageBucket: 'delivery-app-f28d7.firebasestorage.app',
    measurementId: 'G-5LLKHPQEG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZY8nwGs1CUupW9oYuv9G3TeSq0l-25_A',
    appId: '1:412250890587:android:1a814adf101996a6aefa7e',
    messagingSenderId: '412250890587',
    projectId: 'delivery-app-f28d7',
    storageBucket: 'delivery-app-f28d7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB5mCB_BhXnw1nakUa9sf2xbh5dkVvnjs',
    appId: '1:412250890587:web:96649a5b24de4778aefa7e',
    messagingSenderId: '412250890587',
    projectId: 'delivery-app-f28d7',
    authDomain: 'delivery-app-f28d7.firebaseapp.com',
    storageBucket: 'delivery-app-f28d7.firebasestorage.app',
    measurementId: 'G-GJ4FZRLLWM',
  );
}
